### ISSUE TITLE
descriptors.json not found

### ISSUE THREAD

**Issue by cyrilakafia** [OlivierBeq/Mold2_pywrapper#1]
This command to view descriptor details gives an error
```
print(mold2.descriptor_detail(15))
# rotatable bond fraction
```

```
FileNotFoundError: [Errno 2] No such file or directory: '...\\descriptor.json'
```

I installed the library using pip install and I am working on windows.

**Comment by OlivierBeq** [comment]
Additionally, I just fixed all the original spelling typos of the original descriptor details in version `0.0.3-post3`.

**Comment by cyrilakafia** [comment]
Working now, thank you!
