### ISSUE TITLE
Mold2 executables not working on Mac

### ISSUE THREAD

**Issue by cyrilakafia** [OlivierBeq/Mold2_pywrapper#3]
Environment: MacBook, M2 Pro

Code to recreate --->

```
from Mold2_pywrapper import Mold2

smiles_list = [
    # erlotinib
    "n1cnc(c2cc(c(cc12)OCCOC)OCCOC)Nc1cc(ccc1)C#C",
    # midecamycin
    "CCC(=O)O[C@@H]1CC(=O)O[C@@H](C/C=C/C=C/[C@@H]([C@@H](C[C@@H]([C@@H]([C@H]1OC)O[C@H]2[C@@H]([C@H]([C@@H]([C@H](O2)C)O[C@H]3C[C@@]([C@H]([C@@H](O3)C)OC(=O)CC)(C)O)N(C)C)O)CC=O)C)O)C",
    # selenofolate
    "C1=CC(=CC=C1C(=O)NC(CCC(=O)OCC[Se]C#N)C(=O)O)NCC2=CN=C3C(=N2)C(=O)NC(=N3)N",
    # cisplatin
    "N.N.Cl[Pt]Cl"
]
mols = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]

mold2 = Mold2()
print(mold2.calculate(mols))
```

Error --->
![WhatsApp Image 2023-06-19 at 22 45 43](https://github.com/OlivierBeq/Mold2_pywrapper/assets/79414187/e3759e0a-ba94-4542-9758-b3e9203d0b3a)

I tried downloading the zip file and installing executables from zip file

![2](https://github.com/OlivierBeq/Mold2_pywrapper/assets/79414187/24f1c872-8c72-4e20-986e-e0830e70d720)

![3](https://github.com/OlivierBeq/Mold2_pywrapper/assets/79414187/356958d4-8f13-4e63-9d4f-22a4f9b1ad30)

**Comment by OlivierBeq** [comment]
@cyrilakafia, as a matter of fact, the Mold2 executable can only be run on a Windows or Linux platform.
